--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JuanantonioVYT/AnnounceBE
build-by-default: true
branches:
- main
projects:
  AnnounceBE:
    path: ""
    icon: "https://www.google.com/search?q=logo+announcement&client=ms-android-xiaomi-rvo3&sca_esv=ecb8cd266217b6f9&sxsrf=ADLYWIKU1u-ogvb0tUYE5v6vR6cC-YLjUA:1725891700828&udm=2&sa=X&ved=2ahUKEwiDnP7Nh7aIAxUdX_EDHfycBHYQ7Al6BAgPEAQ&biw=400&bih=783&dpr=2.7#vhid=6e_JgAQDj0qqJM&vssid=mosaic"
...
