--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JuanantonioVYT/AnnounceBE
build-by-default: true
branches:
- main
projects:
  AnnounceBE:
    path: ""
    icon: "https://github.com/zFrozead0s/AnnounceBE/blob/main/image.png"
...
