--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JuanantonioVYT/AnnounceBE
build-by-default: true
branches:
- main
projects:
  AnnounceBE:
    path: ""
    icon: "https://discord.com/channels/@me/1086763493899915335/1282708805569740851"
...
